STCLI-289 lock webpack to ~5.109.2
Changes in webpack 5.110.0 cause build failures due to issue
https://github.com/webpack/webpack/issues/21844:
```
11:28:15  HookWebpackError: Transform failed with 1 error:
11:28:15  /etc/folio/stripes/node_modules/esbuild/lib/main.js:534:29: ERROR: "minify" must be a boolean
11:28:15      at makeWebpackError (/etc/folio/stripes/node_modules/webpack/lib/errors/HookWebpackError.js:76:9)
...
```
webpack 5.110.0 changed the shape of `optimization.minify` in a way that
makes esbuild unhappy. This smells a bit like the compatibility problems
we have previously discovered between our JS code that may pass a falsey
value to react-query, written in TS, where that
falsey-but-not-strictly-false value is strictly compared to `false`, and
fails. Here, webpack changed from passing `true` to passing an object
(still truthy, of course), but esbuild expects strict `true` and blows
up if it doesn't get it. Anyway, here we are. Isn't this fun?

An emergency fix in platform-lsp pinned the version at the platform level
under FOLIO-4563. This PR pins it at the source, where `webpack` is a
direct dependency. See STRIPES-1043 for a fix in stripes-build.

Refs STCLI-289